version: '3'

volumes:
  pg_data_kittygram:
  static_kittygram:
  media_kittygram:

services:
  
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data
  
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_kittygram:/backend_static
      - media_kittygram:/app/media
    depends_on:
      - db
  
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static_kittygram:/static
  
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static_kittygram:/static
      - media_kittygram:/media
